// Generated by gen/tools/make_zoo.py: the rest of Doom's bestiary as Grey Matter FC's animal players.
// Each keeps the health, size and job of the monster it replaces (the parrot spits chicks like the Pain Elemental,
// the chick charges like a Lost Soul, the lion fires TNT like the Cyberdemon), and wears the purple team band.

class SICCow : SICFooty replaces HellKnight
{
	Default
	{
		Health 500;
		Speed 8;
		Radius 24;
		Height 64;
		Mass 1000;
		PainChance 50;
		Tag "Cow Defender";
		Obituary "%o was outplayed by the Cow Defender.";
	}
	States
	{
	Spawn:
		SCOW A 10 A_Look;
		SCOW C 10 A_Look;
		Loop;
	See:
		SCOW ABCD 3 A_Chase;
		Loop;
	Missile:
		SCOW E 8 A_FaceTarget;
		SCOW F 6 A_KickAt("SICBigBall");
		SCOW E 6;
		Goto See;
	Pain:
		SCOW G 3;
		SCOW G 3 A_Pain;
		Goto See;
	Death:
		SCOW H 4 A_Scream;
		SCOW I 4 A_NoBlocking;
		SCOW J 4;
		SCOW K 30;
		SCOW K 1 A_Vanish;
		Stop;
	XDeath:
		SCOW H 3 A_Shatter;
		SCOW I 3 A_NoBlocking;
		SCOW JK 3;
		SCOW K 1 A_Vanish;
		Stop;
	}
}

class SICElephant : SICFooty replaces BaronOfHell
{
	Default
	{
		Health 1000;
		Speed 8;
		Radius 26;
		Height 70;
		Mass 1000;
		PainChance 50;
		Tag "Elephant Sweeper";
		Obituary "%o was outplayed by the Elephant Sweeper.";
		+BOSSDEATH
	}
	States
	{
	Spawn:
		SELE A 10 A_Look;
		SELE C 10 A_Look;
		Loop;
	See:
		SELE ABCD 3 A_Chase;
		Loop;
	Missile:
		SELE E 8 A_FaceTarget;
		SELE F 6 A_KickAt("SICBigBall", 8, 2);
		SELE E 6;
		Goto See;
	Pain:
		SELE G 3;
		SELE G 3 A_Pain;
		Goto See;
	Death:
		SELE H 4 A_Scream;
		SELE I 4 A_NoBlocking;
		SELE J 4;
		SELE K 30 A_BossDeath;
		SELE K 1 A_Vanish;
		Stop;
	XDeath:
		SELE H 3 A_Shatter;
		SELE I 3 A_NoBlocking;
		SELE JK 3;
		SELE K 1 A_BossDeath;
		SELE K 1 A_Vanish;
		Stop;
	}
}

class SICBee : SICFooty replaces Cacodemon
{
	Default
	{
		Health 400;
		Speed 8;
		Radius 28;
		Height 56;
		Mass 400;
		PainChance 128;
		Tag "Bumble Winger";
		Obituary "%o was outplayed by the Bumble Winger.";
		+FLOAT
		+NOGRAVITY
	}
	States
	{
	Spawn:
		SBEE A 10 A_Look;
		SBEE C 10 A_Look;
		Loop;
	See:
		SBEE ABCD 3 A_Chase;
		Loop;
	Missile:
		SBEE E 6 A_FaceTarget;
		SBEE F 6 A_KickAt("SICStingBall");
		SBEE E 6;
		Goto See;
	Pain:
		SBEE G 3;
		SBEE G 3 A_Pain;
		Goto See;
	Death:
		SBEE H 4 A_Scream;
		SBEE I 4 A_NoBlocking;
		SBEE J 4;
		SBEE K 30;
		SBEE K 1 A_Vanish;
		Stop;
	}
}

class SICChick : SICFooty replaces LostSoul
{
	Default
	{
		Health 100;
		Speed 8;
		Radius 16;
		Height 40;
		Mass 50;
		PainChance 256;
		Tag "Chick Missile";
		Obituary "%o was outplayed by the Chick Missile.";
		+FLOAT
		+NOGRAVITY
		+DONTFALL
		+NOICEDEATH
		Damage 3;
		MissileChanceMult 0.5;
	}
	States
	{
	Spawn:
		SCHK A 10 A_Look;
		SCHK C 10 A_Look;
		Loop;
	See:
		SCHK ABCD 3 A_Chase;
		Loop;
	Missile:
		SCHK E 10 A_FaceTarget;
		SCHK F 4 A_StartSound("sic/mobsight", CHAN_VOICE);
		SCHK F 4 A_SkullAttack;
		SCHK F 4;
		SCHK F 4;
		Goto Missile+3;
	Pain:
		SCHK G 3;
		SCHK G 3 A_Pain;
		Goto See;
	Death:
		SCHK H 4 A_Scream;
		SCHK I 4 A_NoBlocking;
		SCHK J 4;
		SCHK K 30;
		SCHK K 1 A_Vanish;
		Stop;
	}
}

class SICGiraffe : SICFooty replaces Revenant
{
	Default
	{
		Health 300;
		Speed 10;
		Radius 20;
		Height 72;
		Mass 500;
		PainChance 100;
		Tag "Giraffe Header";
		Obituary "%o was outplayed by the Giraffe Header.";
		MissileChanceMult 0.5;
	}
	States
	{
	Spawn:
		SGIR A 10 A_Look;
		SGIR C 10 A_Look;
		Loop;
	See:
		SGIR ABCD 3 A_Chase;
		Loop;
	Missile:
		SGIR E 8 A_FaceTarget;
		SGIR F 6 A_KickAt("SICHeaderBall");
		SGIR E 8;
		Goto See;
	Pain:
		SGIR G 3;
		SGIR G 3 A_Pain;
		Goto See;
	Death:
		SGIR H 4 A_Scream;
		SGIR I 4 A_NoBlocking;
		SGIR J 4;
		SGIR K 30;
		SGIR K 1 A_Vanish;
		Stop;
	XDeath:
		SGIR H 3 A_Shatter;
		SGIR I 3 A_NoBlocking;
		SGIR JK 3;
		SGIR K 1 A_Vanish;
		Stop;
	}
}

class SICHog : SICFooty replaces Fatso
{
	Default
	{
		Health 600;
		Speed 8;
		Radius 30;
		Height 64;
		Mass 1000;
		PainChance 80;
		Tag "Hog Goalhanger";
		Obituary "%o was outplayed by the Hog Goalhanger.";
		+BOSSDEATH
		SeeSound "sic/pigsquee";
		PainSound "sic/pigsquee";
		DeathSound "sic/pigsquee";
	}
	States
	{
	Spawn:
		SHOG A 10 A_Look;
		SHOG C 10 A_Look;
		Loop;
	See:
		SHOG ABCD 3 A_Chase;
		Loop;
	Missile:
		SHOG E 14 A_FaceTarget;
		SHOG F 6 A_KickAt("SICFireBall", 10, 3);
		SHOG E 6 A_FaceTarget;
		SHOG F 6 A_KickAt("SICFireBall", 10, 3);
		SHOG E 6;
		Goto See;
	Pain:
		SHOG G 3;
		SHOG G 3 A_Pain;
		Goto See;
	Death:
		SHOG H 4 A_Scream;
		SHOG I 4 A_NoBlocking;
		SHOG J 4;
		SHOG K 30 A_BossDeath;
		SHOG K 1 A_Vanish;
		Stop;
	XDeath:
		SHOG H 3 A_Shatter;
		SHOG I 3 A_NoBlocking;
		SHOG JK 3;
		SHOG K 1 A_BossDeath;
		SHOG K 1 A_Vanish;
		Stop;
	}
}

class SICCrab : SICFooty replaces Arachnotron
{
	Default
	{
		Health 500;
		Speed 12;
		Radius 56;
		Height 76;
		Mass 600;
		PainChance 128;
		Tag "Crab Sidestepper";
		Obituary "%o was outplayed by the Crab Sidestepper.";
		+BOSSDEATH
	}
	States
	{
	Spawn:
		SCRB A 10 A_Look;
		SCRB C 10 A_Look;
		Loop;
	See:
		SCRB ABCD 3 A_Chase;
		Loop;
	Missile:
		SCRB E 10 A_FaceTarget;
		SCRB F 3 A_KickAt("SICStingBall");
		SCRB E 3 A_FaceTarget;
		SCRB F 3 A_KickAt("SICStingBall");
		SCRB E 3 A_FaceTarget;
		SCRB F 3 A_KickAt("SICStingBall");
		SCRB E 1 A_SpidRefire;
		Goto Missile+1;
	Pain:
		SCRB G 3;
		SCRB G 3 A_Pain;
		Goto See;
	Death:
		SCRB H 4 A_Scream;
		SCRB I 4 A_NoBlocking;
		SCRB J 4;
		SCRB K 30 A_BossDeath;
		SCRB K 1 A_Vanish;
		Stop;
	XDeath:
		SCRB H 3 A_Shatter;
		SCRB I 3 A_NoBlocking;
		SCRB JK 3;
		SCRB K 1 A_BossDeath;
		SCRB K 1 A_Vanish;
		Stop;
	}
}

class SICParrot : SICFooty replaces PainElemental
{
	Default
	{
		Health 400;
		Speed 8;
		Radius 31;
		Height 56;
		Mass 400;
		PainChance 128;
		Tag "Parrot Playmaker";
		Obituary "%o was outplayed by the Parrot Playmaker.";
		+FLOAT
		+NOGRAVITY
	}
	States
	{
	Spawn:
		SPRT A 10 A_Look;
		SPRT C 10 A_Look;
		Loop;
	See:
		SPRT ABCD 3 A_Chase;
		Loop;
	Missile:
		SPRT E 6 A_FaceTarget;
		SPRT F 8 A_PainAttack("SICChick");
		SPRT E 8;
		Goto See;
	Pain:
		SPRT G 3;
		SPRT G 3 A_Pain;
		Goto See;
	Death:
		SPRT H 4 A_Scream;
		SPRT I 4 A_PainDie("SICChick");
		SPRT J 4;
		SPRT K 30;
		SPRT K 1 A_Vanish;
		Stop;
	}
}

class SICMonkey : SICFooty replaces Archvile
{
	Default
	{
		Health 700;
		Speed 15;
		Radius 20;
		Height 56;
		Mass 500;
		PainChance 10;
		Tag "Monkey Trickster";
		Obituary "%o was outplayed by the Monkey Trickster.";
		+QUICKTORETALIATE
	}
	States
	{
	Spawn:
		SMNK A 10 A_Look;
		SMNK C 10 A_Look;
		Loop;
	See:
		SMNK ABCD 3 A_Chase;
		Loop;
	Missile:
		SMNK E 8 A_FaceTarget;
		SMNK F 6 A_KickAt("SICFireBall", 14, 5);
		SMNK E 10;
		Goto See;
	Pain:
		SMNK G 3;
		SMNK G 3 A_Pain;
		Goto See;
	Death:
		SMNK H 4 A_Scream;
		SMNK I 4 A_NoBlocking;
		SMNK J 4;
		SMNK K 30;
		SMNK K 1 A_Vanish;
		Stop;
	XDeath:
		SMNK H 3 A_Shatter;
		SMNK I 3 A_NoBlocking;
		SMNK JK 3;
		SMNK K 1 A_Vanish;
		Stop;
	}
}

class SICTiger : SICFooty replaces SpiderMastermind
{
	Default
	{
		Health 3000;
		Speed 12;
		Radius 60;
		Height 116;
		Mass 1000;
		PainChance 40;
		Tag "Tiger Captain";
		Obituary "%o was outplayed by the Tiger Captain.";
		+BOSS
		+BOSSDEATH
		+DONTMORPH
		+NORADIUSDMG
	}
	States
	{
	Spawn:
		STIG A 10 A_Look;
		STIG C 10 A_Look;
		Loop;
	See:
		STIG ABCD 3 A_Chase;
		Loop;
	Missile:
		STIG E 16 A_FaceTarget;
		STIG F 3 A_KickAt("SICEnemyBall", 6, 2);
		STIG E 3 A_FaceTarget;
		STIG F 3 A_KickAt("SICEnemyBall", 6, 2);
		STIG E 1 A_SpidRefire;
		Goto Missile+1;
	Pain:
		STIG G 3;
		STIG G 3 A_Pain;
		Goto See;
	Death:
		STIG H 4 A_Scream;
		STIG I 4 A_NoBlocking;
		STIG J 4;
		STIG K 30 A_BossDeath;
		STIG K 1 A_Vanish;
		Stop;
	XDeath:
		STIG H 3 A_Shatter;
		STIG I 3 A_NoBlocking;
		STIG JK 3;
		STIG K 1 A_BossDeath;
		STIG K 1 A_Vanish;
		Stop;
	}
}

class SICLion : SICFooty replaces Cyberdemon
{
	Default
	{
		Health 4000;
		Speed 16;
		Radius 40;
		Height 110;
		Mass 1000;
		PainChance 20;
		Tag "Lion King of the Pitch";
		Obituary "%o was outplayed by the Lion King of the Pitch.";
		+BOSS
		+BOSSDEATH
		+DONTMORPH
		+NORADIUSDMG
	}
	States
	{
	Spawn:
		SLIO A 10 A_Look;
		SLIO C 10 A_Look;
		Loop;
	See:
		SLIO ABCD 3 A_Chase;
		Loop;
	Missile:
		SLIO E 10 A_FaceTarget;
		SLIO F 8 A_KickAt("SICTNTRocket");
		SLIO E 8 A_FaceTarget;
		SLIO F 8 A_KickAt("SICTNTRocket");
		SLIO E 8 A_FaceTarget;
		SLIO F 8 A_KickAt("SICTNTRocket");
		SLIO E 10;
		Goto See;
	Pain:
		SLIO G 3;
		SLIO G 3 A_Pain;
		Goto See;
	Death:
		SLIO H 4 A_Scream;
		SLIO I 4 A_NoBlocking;
		SLIO J 4;
		SLIO K 30 A_BossDeath;
		SLIO K 1 A_Vanish;
		Stop;
	XDeath:
		SLIO H 3 A_Shatter;
		SLIO I 3 A_NoBlocking;
		SLIO JK 3;
		SLIO K 1 A_BossDeath;
		SLIO K 1 A_Vanish;
		Stop;
	}
}

class SICPanda : SICFooty replaces WolfensteinSS
{
	Default
	{
		Health 50;
		Speed 8;
		Radius 20;
		Height 56;
		Mass 100;
		PainChance 170;
		Tag "Panda Prankster";
		Obituary "%o was outplayed by the Panda Prankster.";
		DropItem "Clip";
	}
	States
	{
	Spawn:
		SPAN A 10 A_Look;
		SPAN C 10 A_Look;
		Loop;
	See:
		SPAN ABCD 3 A_Chase;
		Loop;
	Missile:
		SPAN E 8 A_FaceTarget;
		SPAN F 4 A_KickAt("SICEnemyBall");
		SPAN E 3 A_FaceTarget;
		SPAN F 4 A_KickAt("SICEnemyBall");
		SPAN E 6;
		Goto See;
	Pain:
		SPAN G 3;
		SPAN G 3 A_Pain;
		Goto See;
	Death:
		SPAN H 4 A_Scream;
		SPAN I 4 A_NoBlocking;
		SPAN J 4;
		SPAN K 30;
		SPAN K 1 A_Vanish;
		Stop;
	XDeath:
		SPAN H 3 A_Shatter;
		SPAN I 3 A_NoBlocking;
		SPAN JK 3;
		SPAN K 1 A_Vanish;
		Stop;
	}
}

// Heavier balls for the big animals, a stinging ball for the flyers, and a header that curls after you.
class SICBigBall : SICEnemyBall
{
	Default
	{
		Speed 18;
		Scale 0.45;
		DamageFunction (random(2, 8) * 4);
		Translation "0:255=%[0.1,0.1,0.25]:[1.0,1.2,2.0]";
	}
}

class SICStingBall : SICEnemyBall
{
	Default
	{
		Speed 22;
		Gravity 0;
		Scale 0.25;
		DamageFunction (random(2, 6) * 3);
		Translation "0:255=%[0.25,0.2,0.0]:[2.0,1.8,0.4]";
	}
}

class SICHeaderBall : SICEnemyBall
{
	Default
	{
		Speed 12;
		Gravity 0;
		+SEEKERMISSILE
		DamageFunction (random(1, 8) * 6);
		Translation "0:255=%[0.25,0.15,0.0]:[2.0,1.6,0.6]";
	}
	override void PostBeginPlay()
	{
		Super.PostBeginPlay();
		if (target) tracer = target.target;
	}
	override void Tick()
	{
		Super.Tick();
		if (bDestroyed || isFrozen()) return;
		if (level.maptime % 3 == 0) A_SeekerMissile(4, 6);
		if (level.maptime % 2 == 0) SICCube.Make(pos, 'G', 0.25, (0, 0, 0), 10, 0);
	}
}
